import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeSwitcher from "./components/app/components/ThemeSwitcher";
import { Providers } from "./provider";
import Link from "next/link";
import TanstackProvider from "@/providers/TanstackProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gibahtech Tamplate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TanstackProvider>
          <Providers>
            <header className="py-8">
              <nav className="container flex items-center justify-between">
                <ul>
                  <li>
                    <Link href="/" className="text-md font-semibold">
                      Home
                    </Link>
                  </li>
                </ul>
                <ThemeSwitcher />
              </nav>
            </header>
          </Providers>

          <main className="flex m-h-screen flex-col container mt-4 justify-center items-center">
            <h2 className="text-xl md:text-2xl font-bold">Hallo Gibahtech</h2>
            {children}
          </main>
        </TanstackProvider>
      </body>
    </html>
  );
}
